version: "3"
tasks:
  sb-up:
    desc: Start supabase
    cmds:
      - npx supabase start --exclude gotrue,realtime,storage-api,imgproxy,kong,mailpit,studio,edge-runtime,logflare,vector,supavisor

  verify:
    desc: Run formatter, linter, and tests
    cmds:
      - pnpm run fmt
      - pnpm run lint
      - pnpm run test
      - pnpm run build
