version: "3"
tasks:
  start-env:
    desc: Start supabase
    dotenv:
      - supabase/functions/.env.dev
    cmds:
      - supabase start
      - ngrok http 54321 --url $SUPABASE_URL &
      - curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/setWebhook" -d "url=$SUPABASE_URL/functions/v1/telegram-webhook"
      - supabase functions serve --no-verify-jwt --env-file supabase/functions/.env.dev

  stop-env:
    desc: Start supabase
    cmds:
      - supabase stop
      - pkill ngrok || true
      - pkill functions || true

  run:
    desc: Run the development server
    cmds:
      - task: start-env
      - pnpm run dev

  integration-test:
    desc: Run integration tests
    cmds:
      - pnpm run test:integration

  apply:*:
    desc: Apply dev infrastructure changes
    dir: ./terraform/application
    vars:
      ENVIRONMENT: "{{index .MATCH 0}}"
    cmds:
      - terraform init -backend-config=config/{{.ENVIRONMENT}}.hcl -reconfigure
      - terraform apply -var-file=config/{{.ENVIRONMENT}}.tfvars -var-file=config/{{.ENVIRONMENT}}.secret.tfvars

  deploy:*:
    desc: Deploy to specified environment
    vars:
      ENVIRONMENT: "{{index .MATCH 0}}"
    cmds:
      - task: "apply:{{.ENVIRONMENT}}"
      - supabase secrets set --env-file supabase/functions/.env.prod
      - supabase functions deploy telegram-webhook --no-verify-jwt
      - supabase functions deploy telegram-auth --no-verify-jwt
      - |
        source supabase/functions/.env.{{.ENVIRONMENT}}
        curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/setWebhook" -d "url=${SUPABASE_URL}/functions/v1/telegram-webhook"

  build:
    desc: Run formatter, linter, and tests
    cmds:
      - pnpm run fmt
      - pnpm run lint
      - pnpm run test
      - pnpm run test:integration
      - pnpm run build
