version: "3"
tasks:
  start-env:
    desc: Start supabase
    cmds:
      - npx supabase start

  stop-env:
    desc: Start supabase
    cmds:
      - npx supabase stop

  verify:
    desc: Run formatter, linter, and tests
    cmds:
      - pnpm run fmt
      - pnpm run lint
      - pnpm run test
      - pnpm run build
