vercel_source_branch     = "dev"
app_domain               = "dev.pulselog.me"
telegram_bot_name        = "@moody-qa"
telegram_bot_url         = "https://t.me/open_mood_tracker_qa_bot"
zone_id                  = "86a8c207a61ad80da2fd1616f1fac5f3"
supabase_url             = "https://iwegsqflyrbynymrvfqa.supabase.co"
supabase_publishable_key = "sb_publishable_LGBKaf-s3vfHy-HFtkvvJQ_1aJ0cR3Q"
