app_domain               = "pulselog.me"
vercel_source_branch     = "main"
zone_id                  = "86a8c207a61ad80da2fd1616f1fac5f3"
supabase_url             = "https://iwegsqflyrbynymrvfqa.supabase.co"
supabase_publishable_key = "sb_publishable_LGBKaf-s3vfHy-HFtkvvJQ_1aJ0cR3Q"
